### ISSUE TITLE
Allow other time zone timestamps

### ISSUE THREAD

**Issue by tslastff** [jaytarang92/bobcat-status-reporter#3]
Current timestamp only shows in UTC which comes from the miner itself.  Would be great to be able to have option to convert it to my local time with daily savings taken into consideration.  👍

**Comment by jtarang** [comment]
This makes sense. I will try to get this in. Should see a PR coming in a few days.

**Comment by jtarang** [comment]
@tslastff There is a pull request for this open now. Would mind testing it before we merge it? Thanks. 
The `README.md` was updated that lists the supported timezone strings to pass it. 
Here is the link for that: https://github.com/python/tzdata/blob/master/src/tzdata/zones

**Comment by tslastff** [comment]
Thanks for getting this feature in.  I've tested the branch and it doesn't seem to be accepting any timezone value I supplied from the list of timezones.  

Example of error:  [Timezone: America/Los_Angeles is not a valid timezone.].  

I'ved tried different values from the list and with single, double and no quotes.  I'm on Python 3.9 (64-bit) on Windows 10.  Let me know what you think I should try.  Thanks again.

**Comment by jtarang** [comment]
Windows needs a package installed. I was developing this on Linux so it wasn't needed. 
` pip install tzdata` . If this works let me know I will add it to the requirements file.

**Comment by tslastff** [comment]
Yup that did it.  I would have thought that the timezone related data library is built into the core engine also.  It's running correctly now.  Thanks again!

**Comment by jtarang** [comment]
Apparently windows doesn't have this installed by default whereas linux does. 

https://pypi.org/project/tzdata/

Thanks for testing . I will merge and push this to main.
